// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RECLAB",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "RECLAB",
            targets: ["AppModule"],
            bundleIdentifier: "com.mayar.reclab",
            teamIdentifier: "65WKCCK99N",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "RECLAB needs camera access to capture and document your experiments."),
                .photoLibrary(purposeString: "RECLAB needs access to your photo library to select photos for your projects."),
                .photoLibraryAdd(purposeString: "RECLAB needs permission to save your captured results to your library.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)